[tool.poetry]
name = "pdf-statements-unlock"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.12"
pypdf = "^4.0.0"
pycryptodome = "^3.20.0"
python-dotenv = "^1.0.1"
pydantic = "^2.9.0"
pydantic-settings = "^2.4.0"
starlette = "^0.38.4"


[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
profile = "black"
